### ISSUE TITLE
Exclude participant drawing another participant's name?

### ISSUE THREAD

**Issue by spencerthayer** [GuilleGF/SecretSantaPHP#2]
**Exclude participant drawing another participant's name?**
How would we exclude certain participants from being randomly selected another participant's name? Use case example: Family member A doesn't talk to family member Z.

**Comment by GuilleGF** [comment]
Now you can add multiple exclusive players, I hope this solves your case.

**Comment by spencerthayer** [comment]
WOOT! THANKS!
